server:
  address: 127.0.0.1
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://121.199.74.176:3306/quartz?useUnicode=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver